const throwError = (err) => new Promise((_, reject) => reject(err))

export default throwError
